version: "3.9"
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=password
    restart: always
    volumes:
      - .:/bitnami/redis/data
    # ports:
    #   - 6379:6379

  server:
    build: "."
    container_name: server
    hostname: "0.0.0.0"
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
